server:
  port: 8789

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    mongodb:
      uri: ${ATLAS_URI}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Spring Cloud LoadBalancer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


app:
  cart:
    tax-rate: 0.1
  kafka:
    topic:

logging:
  level:
    org.springframework.security: DEBUG
