services:
  sonarqube-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - sonarqube-db:/var/lib/postgresql/data
    networks:
      - buy-two-net

  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      SONAR_WEB_JAVA_OPTS: "-Xms256m -Xmx256m"
      SONAR_CE_JAVA_OPTS: "-Xms256m -Xmx256m"
    deploy:
      resources:
        limits:
          memory: 1500M
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
    networks:
      - buy-two-net

volumes:
  sonarqube-db:
  sonarqube-data:
  sonarqube-logs:

networks:
  buy-two-net:
    external: true
    name: buy-two_java-jenk_sonarnet
