version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "9090:8080"   # Jenkins UI
      - "50000:50000" # Agent port (future use)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # so Jenkins can run docker builds
    environment:
      - JAVA_OPTS=-Xmx2048m -Xms1024m

volumes:
  jenkins_home:
